---

- name: Set kernel cmdline
  lineinfile:
    path: /boot/cmdline.txt
    regexp: '^root=(.*) rw (.*)$'
    line: 'root=\1 rw rootwait console=serial0,115200 console=tty3 selinux=0 quiet splash plymouth.ignore-serial-consoles smsc95xx.turbo_mode=N dwc_otg.lpm_enable=0 kgdboc=serial0,115200 usbhid.mousepoll=8 audit=0 systemd.unified_cgroup_hierarchy=0 cgroup_memory=1 cgroup_enable=memory'
    backrefs: true
  notify: reboot
