---
k3s_version: v1.24.0-rc1+k3s1
ansible_user: bun
systemd_dir: /etc/systemd/system
master_ip: "{{ hostvars[groups['loadbalancer'][0]]['ansible_host'] | default(groups['loadbalancer'][0]) }}"
k3s_token: "1aa588e1671c9050920f60bb9e3ddbdef2bbd719b143a5cb1f37cf3c33381e9d"

extra_server_args: "--tls-san {{ master_ip }}"
# "--disable servicelb --disable traefik"
extra_agent_args: ""
